rc: modernize

diff --git a/rc b/rc
--- a/rc
+++ b/rc
@@ -1,36 +1,112 @@
 #!/usr/bin/env bash
-# rc - enable/disable/start/stop/etc daemons
+# rc - enable/disable/start/stop/etc daemons - version 0.1
+# usage: rc [-h ssh-enabled-host.com] (start|stop|restart|enable|disable|[list]|help)
+# Control the currently running daemons. Works with systemd and upstart.
 #
-# Copyright 2014-2015 Kylie McClain <somasis@exherbo.org>
+# Arguments:
+#      -h [ssh-enabled-host.com]
+#           Connect to a host using SSH and control it's init daemon.
+#           (requires sudo and bash on remote host)
+#
+# Actions:
+#      start <daemon>
+#           Start the <daemon> given.
+#
+#      stop <daemon>
+#           Stop the <daemon> given.
+#
+#      restart <daemon>
+#           Restart the <daemon> given.
+#
+#      enable <daemon>
+#           Enable the <daemon> given to run at startup.
+#
+#      disable <daemon>
+#           Disable the <daemon> given from running at startup.
+#
+#      list
+#           List the status of all daemons.
+#
 # Distributed under the terms of the ISC License
 # https://github.com/somasis/scripts/
+# End of help.
+# Copyright (c) 2014-2015 Kylie McClain <somasis@exherbo.org>
+# Permission to use, copy, modify, and/or distribute this software for any
+# purpose with or without fee is hereby granted, provided that the above
+# copyright notice and this permission notice appear in all copies.
+#
+# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
+# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
+# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
+# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
+# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
+# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
+# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
+#
+# End of copyright.
+
+COLOR_RESET=$'\033[1;0m'
+COLOR_BOLD_RED=$'\033[1;31m'
+COLOR_BOLD_GREEN=$'\033[1;32m'
+COLOR_BOLD_YELLOW=$'\033[1;33m'
+COLOR_BOLD_BLUE=$'\033[1;34m'
 
 ## Settings
 excluded_daemons=( "systemd-.*" "user@.*" "getty@.*" )
-common_location='$SCRIPT_DIR/common.sh'
-if [[ -z "$config_location" ]];then
-    config_location='$XDG_CONFIG_HOME/rc.conf'
-fi
 
-## Script begins here
-script_arguments="[--host=ssh-enabled-host.com | -h ssh-enabled-host.com] (start|stop|restart|enable|disable|[list]|help)"
-script_description="A script to make managing of daemons much easier.\nCurrently for Upstart/SysV, and systemd systems only."
-script_credit="Written by Kylie McClain <https://github.com/somasis>, ISC license."
+help() {
+    sed -n '/^#/!d;s/^# //;s/^#//;3,${p;}' "$0" | \
+        while IFS= read help_line;do
+            if [[ "$help_line" == "End of help." ]];then
+                exit 0
+            else
+                printf "%s\n" "$help_line"
+            fi
+        done
+    exit 0
+}
 
-XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
+version() {
+    sed 's/^# //;s/.* - version/'"${0##*/}"'/;2q;$!d' "$0"
+    copyright
+    exit 0
+}
+
+copyright() {
+    sed -n '/^#/!d;s/^# //;s/^#//;/End of help./,${p;}' "$0" | \
+    while IFS= read copyright_line;do
+        if [[ "$copyright_line" == "End of help." ]];then
+            true
+        elif [[ "$copyright_line" == "End of copyright." ]];then
+            break
+        else
+            printf "%s\n" "$copyright_line"
+        fi
+    done
+}
+
+stderr() { # stderr <msg>
+    echo "$@" >&2
+}
+
+die() { # die <err msg> <err code> or die <err code>
+    if [[ "$#" -gt 1 ]];then
+        local err_msg="$1"
+        local err_code="$2"
+        stderr "$me: $err_msg; dying"
+    else
+        local err_code="$1"
+    fi
+    exit $err_code
+}
+
 SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
-eval "common_location=$common_location"
-eval "config_location=$config_location"
-. "$config_location" 2>/dev/null >/dev/null
 
 # bootstrap_ssh(): bootstraps the script for usage on any ssh server
 #                  since we get the content of common.sh and the config
 #                  without needing it on the remote host
 bootstrap_ssh() {
-    (cat "$SCRIPT_DIR/common.sh" 2>/dev/null
-     echo
-     cat "$XDG_CONFIG_HOME/rc.conf" 2>/dev/null
-     cat "$SCRIPT_DIR/${0##*/}" 2>/dev/null) | ssh "$host" -- sudo bash -$- /dev/stdin "$@" 2>&1
+    cat "$SCRIPT_DIR/${0##*/}" 2>/dev/null | ssh "$host" -- sudo bash -$- /dev/stdin "$@" 2>&1
     bootstrap_ssh_error="$?"
     exit "$bootstrap_ssh_error"
 }
@@ -120,8 +196,8 @@ do_action() {
         old_action=
     elif [[ "$action" == "list" || -z "$action" ]];then
         list_init
-    elif [[ "$action" == "help" ]];then
-        show_help 0
+    elif [[ "$action" == "help" || "$action" == "--help" ]];then
+        help
     else
         if [[ "$init_system" == @(upstart|init) ]];then
             if [[ -f "/etc/init.d/$daemon" ]];then
@@ -138,30 +214,27 @@ do_action() {
     old_action=
 }
 
-if [[ "$1" == "--host="* ]];then
-    host="$1"
-    host=$(echo "$host" | cut -d'=' -f2-)
+if [[ "$1" == "-h" ]];then
     shift
-    bootstrap_ssh
-elif [[ "$1" == "-h" ]];then
     host="$2"
-    shift;shift
+    shift || die "You need to provide a host."
     bootstrap_ssh
 fi
 
-if [[ -z "$SSH_CONNECTION" ]];then
-    . "$SCRIPT_DIR/common.sh" 2>/dev/null >/dev/null
+if [[ -r /proc/1/comm ]];then
+    init_system=$(</proc/1/comm)
+elif type -fPp systemctl >/dev/null 2>&1;then
+    init_system=systemd
+else
+    init_system=init
 fi
-
-init_system=$(</proc/1/comm)
 
 action="$1"
 action=$(echo "$action" | tr '[A-Z]' '[a-z]')
 
 if [[ "$UID" -ne 0 ]]; then
     exec sudo bash -$- "$SCRIPT_DIR/${0##*/}" "$action" "$@"
-    exit_code="$?"
-    exit "$exit_code"
+    die "sudo failed" "$err_sudo_failed"
 fi
 
 if [[ "$init_system" == "systemd" ]];then
